server:
  port: 8031
spring:
  application:
    name: 07-spring-cloud-hystrix-turbine
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
turbine:
  appConfig: 07-spring-cloud-consumer-ribbon-hystrix,07-spring-cloud-consumer-feign-hystrix-fallback-stream
  clusterNameExpression: "'default'"