server:
  port: 8010
provider:
  url: http://localhost:8000/user/

spring:
  application:
    name: 10-spring-cloud-consumer-trace-zipkin
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0