spring:
  application:
    name: 04-spring-cloud-eureka-ha
server:
  port: 8762                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/