server:
  port: 8010
spring:
  application:
    name: 06-spring-cloud-consumer-feign-custom
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true